// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWAEfi_0_Jovu-G-E0ydCczH2KPAcWYEg',
    appId: '1:1027256312969:web:709f67761621f255245258',
    messagingSenderId: '1027256312969',
    projectId: 'loginpage-cli',
    authDomain: 'loginpage-cli.firebaseapp.com',
    storageBucket: 'loginpage-cli.appspot.com',
    measurementId: 'G-8PLCNGCX4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCpmkciAVMdO4bSVr7v1Eq500yXBQZM9U',
    appId: '1:1027256312969:android:96c5f2fee741e324245258',
    messagingSenderId: '1027256312969',
    projectId: 'loginpage-cli',
    storageBucket: 'loginpage-cli.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfjhxCJ8GM4YaUTJSF4xys5z3DEKtiAKA',
    appId: '1:1027256312969:ios:a28396de5e3d6ad7245258',
    messagingSenderId: '1027256312969',
    projectId: 'loginpage-cli',
    storageBucket: 'loginpage-cli.appspot.com',
    iosBundleId: 'loginpage.com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfjhxCJ8GM4YaUTJSF4xys5z3DEKtiAKA',
    appId: '1:1027256312969:ios:a28396de5e3d6ad7245258',
    messagingSenderId: '1027256312969',
    projectId: 'loginpage-cli',
    storageBucket: 'loginpage-cli.appspot.com',
    iosBundleId: 'loginpage.com.example.loginPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWAEfi_0_Jovu-G-E0ydCczH2KPAcWYEg',
    appId: '1:1027256312969:web:b77fe2b72a38e9a2245258',
    messagingSenderId: '1027256312969',
    projectId: 'loginpage-cli',
    authDomain: 'loginpage-cli.firebaseapp.com',
    storageBucket: 'loginpage-cli.appspot.com',
    measurementId: 'G-H1MFY9HHVQ',
  );
}
